---
title: "Analysis"
output: html_document
date: "2023-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#load libraries
library(tidyverse)
library(leaps)
library(boot)
library(GGally)

#get data
setwd("C:/Users/david/Phan_DSPN_S23/DSPN_Final/Data")
df = read.csv("deck_data")

head(df)
names(df)
names(df)[names(df) == 'X'] <- 'deck'

#categorize archetypes into aggro, control, or combo
df = df %>%
  mutate(archetype=case_when(grepl("Aggro",archetype) ~ 'Aggro',
                            grepl("Control",archetype) ~ 'Control',
                            grepl("Combo",archetype) ~ 'Combo',
                            TRUE ~ archetype))

#categorize unique archetypes
#mtgtop8 categorizes these but I couldn't figure out how to extract that
unique(df$archetype)
df = df %>% mutate(archetype=case_when(
    archetype %in% c("WeenieWhite","DevotiontoGreen","RedDeckWins","Angels",
                    "ArclightPhoenix","Auras","Elves","Humans","Dragons",
                    "Goblins","Affinity","Merfolk") ~ "Aggro",
    archetype %in% c("FiresofInvention","Jund","OmnathRamp",
                     "NivMizzetReborn","GreenRamp","Enchantress") ~ "Control",
    archetype %in% c("JeskaiAscendancy","LotusField","Winota","Greasefang",
                    "Creativity","Transmogrify","GreasefangParhelion",
                    "Reanimator","NeoformAtraxa","Gyruda","Dragonstorm",
                    "KinnanEmry","TaintedOracle","JeskaiTurns") ~ "Combo",
    TRUE ~ archetype))

#drop decks without archetypes
drop = which(df$archetype=="Other" | df$archetype=="Combo")
df = df[-drop,]

#control for decksize
df = df %>%
  mutate(MV=MV/(decksize-lands)) %>%
  mutate(across(c(lands:other),~ .*60/decksize)) %>%
  mutate(across(MV0:MV6.,~ .*60/decksize)) %>%
  mutate(across(lands:other,round)) %>%
  mutate(across(MV0:MV6.,round))

#categorize formats
df = df %>% mutate(format=case_when(
                          format %in% c("ST","ALCH") ~ "Rotating",
                          TRUE ~ "Nonrotating"))

#make sure categorical variables are factors
df$archetype = as.factor(df$archetype)
df$companion = as.factor(df$companion)
df$format = as.factor(df$format)

#split the data
set.seed(20495)
test = sample(1:nrow(df),nrow(df)/2)
df_test = df[test,]
df_train = df[-test,]
```

```{r}
#EDA
head(df_train)
summary(df_train)
pairs = df_train %>%
        select(lands,mdfcs,cantrips,ramp,companion,MV,archetype,format) %>%
        ggpairs()
suppressMessages(print(pairs))
```

```{r}
#best fit model
best_fit = matrix(NA,nrow(df_train),3)
for (i in 1:nrow(df_train)){
  glm_cv = regsubsets(lands~MV+mdfcs+cantrips+ramp+companion+archetype+format,
                      df_train[-i,],
                      nvmax=30)
  cv_summary = summary(glm_cv)
  best_fit[i,] = c(which.min(cv_summary$bic),
                  which.max(cv_summary$adjr2),
                  which.min(cv_summary$cp))
}
table(best_fit[,1])
table(best_fit[,2])
table(best_fit[,3])

glm = glm(lands~MV+mdfcs+cantrips+ramp+companion+archetype+format,data=df_train)
summary(glm)
plot(glm)
```

```{r}
#bootstrapping
set.seed(20495)
boot_func <- function(data, index){  
    return(coef(glm(lands~MV+mdfcs+cantrips+ramp+companion+archetype+format,
                    data=data,
                    subset=index)))
  }

boot = boot(df_train,boot_func,R=1000)
boot
```

```{r}
#permutation testing
df_perm = df_train
perm_coefs = matrix(NA,1000,8)
colnames(perm_coefs) = c("intercept",
                         "MV",
                         "mdfcs",
                         "cantrips",
                         "ramp",
                         "companion",
                         "control",
                         "format")

set.seed(20495)
for (i in 1:1000){
  df_perm = df_perm %>% mutate(across(c(MV,mdfcs,cantrips,ramp,companion,
                                        archetype,format),
                                      ~.[sample(nrow(df_perm))]))
  perm_coefs[i,] = coef(glm(lands ~
                            MV+mdfcs+cantrips+ramp+companion+archetype+format,
                            data=df_perm))
}

#plot null distributions
for (i in 1:8){
  hist(perm_coefs[,i],xlab=colnames(perm_coefs)[i])
}

#get p-values
p_values = rep(NA,8)
for (i in 1:8){
  p_values[i] = ifelse(coef(glm)[i] > mean(perm_coefs[,i]),
                  sum(perm_coefs[,i]>coef(glm)[i])/nrow(df_train),
                  sum(perm_coefs[,i]<coef(glm)[i])/nrow(df_train))
}
p_values
```

```{r}
predict = round(predict(glm,df_test))
err = predict - df_test$lands
hist(err)
hist(abs(err))
mean(err)
mean(abs(err))
```


```{r}
summary(glm(lands~MV+ramp+cantrips+mdfcs+companion+archetype,data=df))
#see mana curves
df_train %>% group_by(format,archetype) %>% summarize(median(cantrips))
MV_dist = df_train %>% group_by(format,archetype) %>%
          summarise(across(MV:MV6., mean)) %>%
          mutate(across(MV0:MV6., round)) %>%
          data.frame
MV_dist
MV_dist = df_train %>% group_by(archetype) %>%
          summarise(across(MV:MV6., mean)) %>%
          mutate(across(MV0:MV6., round)) %>%
          data.frame
MV_dist
MV_dist = df_train %>% group_by(format) %>%
          summarise(across(MV:MV6., mean)) %>%
          mutate(across(MV0:MV6., round)) %>%
          data.frame
MV_dist
```







